import '../blocks/text-field/text-field';
import '../blocks/dropdown/dropdown';
import '../blocks/datepicker/datepicker';
import '../blocks/checkbox/checkbox';
import '../blocks/subscription/subscription';
import '../blocks/radio/radio';
import '../blocks/like/like';
import '../blocks/slider-toxin/slider-toxin';
import '../blocks/paginator/paginator';
import '../blocks/dropdown/__button/dropdown__button';
import '../blocks/dropdown/__item/dropdown__item';
import '../favicons/favicons';
import './Form Elements.scss';
