import '../blocks/checkbox/checkbox';
import '../blocks/card-details/card-details';
import '../blocks/datepicker/datepicker';
import '../blocks/dropdown/dropdown';
import '../blocks/dropdown/_guests/dropdown_guests';
import '../blocks/subscription/subscription';
import '../blocks/dropdown/__button/dropdown__button';
import '../blocks/dropdown/__item/dropdown__item';
import '../favicons/favicons';
import './Room details.scss';
