import '../blocks/checkbox/checkbox';
import '../blocks/datepicker/datepicker';
import '../blocks/dropdown/dropdown';
import '../blocks/dropdown/_guests/dropdown_guests';
import '../blocks/slider-toxin/slider-toxin';
import '../blocks/paginator/paginator';
import '../blocks/card-room/card-room';
import '../blocks/subscription/subscription';
import '../blocks/dropdown/__button/dropdown__button';
import '../blocks/dropdown/__item/dropdown__item';
import '../favicons/favicons';
import './Search room.scss';
